services:
  - type: static
    name: interior-estimator
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NPM_VERSION  
        value: "9"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
